### PR TITLE
initial entity reference revisions docs

### PR DESCRIPTION
**Pull request by seth-shaw-asu**

### CODE REVIEW

**Comment by seth-shaw-asu** [comment]
Updated to reflect changes made to the associated PR (https://github.com/mjordan/islandora_workbench/pull/619/commits/9c7799f7cbaad7de2148c1943af09ebb172df619).

**Comment by mjordan** [comment]
Thanks Seth, Tagging @chrisDay50 on this.

**Comment by mjordan** [comment]
Since the REST endpoint(s) required to make this work will not be enabled by default, we should outline how to do that in the docs. @chrisDay50 is this something you could contribute?

**Comment by mjordan** [comment]
I'm going to merge this now so @chrisDay50 can get a clean main branch to work with. Thanks very much @seth-shaw-asu !

**Pull request merged**
